-- ---------------------------------------------------------------------------
-- FHIR Resource Creator - Transform Custom
--
-- Maps an inbound JSON message onto a FHIR resource by hand, using the
-- fhir_creator helpers, and forwards the completed FHIR JSON to the next node
-- (typically the FHIR Validator).
--
-- This is a direct, readable mapping: the developer writes exactly which source
-- fields go where. templates/patient.json is a REFERENCE of the shape being
-- built (generated by the FHIR Profile Designer) - it is not parsed at runtime.
-- The resource is constructed from populated fields only, so there are no
-- unresolved placeholders and no null cleanup step.
--
-- To map a different resource, edit RESOURCE_TYPE and the mapping below, using
-- templates/<resource>.json as your field reference.
-- ---------------------------------------------------------------------------
-- The runtime puts this node's directory on package.path, and the fhir_creator
-- library ships flat here, so it is required by name with no path setup.
local Fhir = require 'fhir_creator'

-- The FHIR version this mapping was designed against. Informational only: it
-- documents intent and is not enforced here. Configure the FHIR Validator with
-- a server of the matching version to actually validate the output.
local FHIR_VERSION  = '4.0.1'
local RESOURCE_TYPE = 'Patient'

-- The identifier system to stamp on the patient's MRN. Comes from here, not
-- from the input, and is never invented if absent.
local IDENTIFIER_SYSTEM = 'http://example.org/mrn'

function main(Data)
   local Ok, Result = pcall(function()
      -- 1. Parse the incoming message.
      local Input = linkiir.json.parse(Data)
      assert(type(Input) == 'table', 'expected an incoming JSON object')

      -- 2. Start a FHIR Patient.
      local Patient = Fhir.new(RESOURCE_TYPE)

      -- 3. Identifier (MRN). The system is configured above and is constant, so
      -- only add an identifier when the input actually carries a value -
      -- otherwise there is no identifier to build (a system with no value is not
      -- one). addIdentifier itself requires both once called.
      if Input.identifier_value ~= nil and Input.identifier_value ~= '' and Input.identifier_value ~= linkiir.json.null then
         Fhir.addIdentifier(Patient, IDENTIFIER_SYSTEM, Input.identifier_value)
      end

      -- 4. Active status - a boolean, and false must be preserved (not dropped).
      if Input.active ~= nil and Input.active ~= linkiir.json.null then
         assert(type(Input.active) == 'boolean', 'Patient.active must be a boolean')
         Patient.active = Input.active
      end

      -- 5. Name.
      Fhir.addName(Patient, Input.given, Input.family)

      -- 6. Contact information.
      Fhir.addTelecom(Patient, 'phone', Input.phone)
      Fhir.addTelecom(Patient, 'email', Input.email)

      -- 7. Gender (normalized) and birth date.
      Patient.gender = Fhir.gender(Input.gender)
      if Input.birthDate ~= nil and Input.birthDate ~= '' and Input.birthDate ~= linkiir.json.null then
         Patient.birthDate = Input.birthDate
      end

      -- 8. Address.
      Fhir.addAddress(Patient, Input)

      -- 9. Serialize.
      return Fhir.toJson(Patient)
   end)

   if not Ok then
      -- A mapping error (bad input, unsupported gender, malformed JSON) is a
      -- failure of this transform: log it and forward nothing. It stays visible
      -- as an error rather than being reported as a successful transformation.
      linkiir.log.error('FHIR Resource Creator: ' .. tostring(Result))
      return
   end

   -- 10. Forward the completed FHIR JSON to the next node (the Validator).
   linkiir.flow.push{ data = Result }
   linkiir.log.info('FHIR Resource Creator: built and forwarded a '
      .. RESOURCE_TYPE .. ' resource (designed for FHIR ' .. FHIR_VERSION .. ').')
end
